var priceList = {
"000" : {
"id" : "000",
"subid" : {},
"name" : "Ким-чи весовая",
"price" : "*",
"composition" : "Состав: пекинская капуста, соль, сахар, пряности, чеснок, перец красный молотый",
"description" : "100г продукта содержат: белок - 1.7г, углеводы - 5.0г Энергетическая ценность: 109.0ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 30 суток",
"imageSource-00" : "<img src='images/final_low_resized/ким-ча_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/редька по-восточному_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/морская капуста_low_resized.png' >"},
"001" : {
"id" : "001",
"subid" : {},
"name" : "Редька по-восточному весовая",
"price" : "*",
"composition" : "Состав: редька, соль, сахар, пряности, чеснок, перец красный молотый",
"description" : "100г продукта содержат: белок - 1.7г, углеводы - 5.0г Энергетическая ценность: 109.0ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 30 суток",
"imageSource-00" : "<img src='images/final_low_resized/редька по-восточному_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/ким-ча_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/морская капуста_low_resized.png' >"},
"002" : {
"id" : "002",
"subid" : {},
"name" : "Морская капуста по-восточному",
"price" : "*",
"composition" : "Состав: морская капуста, морковь, соль, красный и черный перец, чеснок, уксус, кунжутное семя",
"description" : "100г продукта содержат: белок - 9г, жир = 0.2г углеводы - 3.0г Энергетическая ценность: 286.1ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/морская капуста_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/редька по-восточному_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/ким-ча_low_resized.png' >"},
"003" : {
"id" : "003",
"subid" : {},
"name" : "Капуста белокочанная",
"price" : "*",
"composition" : "Состав: капуста, соль, морковь, красный перец, чеснок, сахар",
"description" : "100г продукта содержат: белок - 1.7г, жиры - 0.1г, углеводы - 5.2г Энергетическая ценность: 25ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/капуста по-восточному_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/капуста по-восточному_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/капуста по-восточному_low_resized.png' >"},
"004" : {
"id" : "004",
"subid" : {},
"name" : "Редька с морковью по-восточному",
"price" : "*",
"composition" : "Состав: редька, соль, морковь, красный перец, сахар, уксус, специи",
"description" : "100г продукта содержат: белок - 2.18г, жир - 0.31г, углеводы - 5.81г Энергетическая ценность: 34.01ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/редька с морковкой_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/редька с морковкой_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/редька с морковкой_low_resized.png' >"},
"005" : {
"id" : "005",
"subid" : {},
"name" : "Морковь по-восточному",
"price" : "*",
"composition" : "Состав: кунжут, соль, морковь, черный перец, сахар, уксус, специи",
"description" : "100г продукта содержат: белок - 2.22г, жир - 0.76г углеводы - 8.09г Энергетическая ценность: 37.9ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/морковь по-восточному_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/морковь по-восточному_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/морковь по-восточному_low_resized.png' >"},
"006" : {
"id" : "006",
"subid" : {},
"name" : "Грибы по-восточному",
"price" : "*",
"composition" : "Состав: грибы, морковь, специи, масло растительное, кунжут",
"description" : "100г продукта содержат: белок - 10.45г, жиры - 2.56г, углеводы - 5.31г Энергетическая ценность: 85.12ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/грибы по-восточному_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/грибы по-восточному_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/грибы по-восточному_low_resized.png' >"},
"007" : {
"id" : "007",
"subid" : {},
"name" : "Салат Пекинский",
"price" : "*",
"composition" : "Состав: капуста, соль, морковь, красный перец, чеснок, уксус, редька, огурец, сахар, специи",
"description" : "100г продукта содержат: белок - 1.4г, жир - 10г, углеводы - 4.2г Энергетическая ценность: 111.8ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/салат пекинский_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/салат пекинский_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/салат пекинский_low_resized.png' >"},
"008" : {
"id" : "008",
"subid" : {},
"name" : "Щике",
"price" : "*",
"composition" : "Состав: камбала, редька, соль, красный перец, пряности, чеснок, сахар",
"description" : "100г продукта содержат: белок - 24.3г, жир - 9.6г, углеводы - 5.0г Энергетическая ценность: 184.0ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/щике_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/щике_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/щике_low_resized.png' >"},
"009" : {
"id" : "009",
"subid" : {},
"name" : "Кактуги",
"price" : "*",
"composition" : "Состав: кета, редька, соль, пряности, чеснок, сахар, перец красный молотый",
"description" : "100г продукта содержат: белок - 24.3г, жир - 9.6г, углеводы - 5.0г Энергетическая ценность: 184.0ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/кактуги с кетой_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/кактуги с кетой_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/кактуги с кетой_low_resized.png' >"},
"010" : {
"id" : "010",
"subid" : {},
"name" : "Каракатица",
"price" : "*",
"composition" : "Состав: каракатица, стручковый перец, соль, красный перец, пряности, чеснок, сахар",
"description" : "100г продукта содержат: белок - 16.2г, жир - 0.7г, углеводы - 0.8г Энергетическая ценность: 79ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/каракатица_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/каракатица_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/каракатица_low_resized.png' >"},
"011" : {
"id" : "011",
"subid" : {},
"name" : "Квашеная капуста",
"price" : "*",
"composition" : "Состав: капуста, морковь, соль, сахар, перец горошек, лавровый лист",
"description" : "100г продукта содержат: белок - 1.7г, жир - 0.1г, углеводы - 5.2г Энергетическая ценность: 25ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 30 суток",
"imageSource-00" : "<img src='images/final_low_resized/квашеная капуста_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/квашеная капуста_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/квашеная капуста_low_resized.png' >"},
"012" : {
"id" : "012",
"subid" : {},
"name" : "Горчица",
"price" : "*",
"composition" : "Состав: горчичный порошок, соль, масло растительное, уксус, сахар, специи, вода",
"description" : "100г продукта содержат: белок - 1.7г, углеводы - 5.0г Энергетическая ценность: 164.6ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 0&#176; до 10&#176; - 45 суток",
"imageSource-00" : "<img src='images/final_low_resized/горчица_low_resized.png' >",
"imageSource-01" : "<img src='images/final_low_resized/горчица_low_resized.png' >",
"imageSource-02" : "<img src='images/final_low_resized/горчица_low_resized.png' >"}
};
