var priceList = {
"000" : {
"id" : "000",
"subid" : {},
"name" : "1",
"price" : "*",
"composition" : "Состав: 1",
"description" : "100г продукта содержат: белок - 1.7г, углеводы - 5.0г Энергетическая ценность: 109.0ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 30 суток",
"imageSource-00" : "<img src='images/final_low_resized/1.png' >",
"imageSource-01" : "<img src='images/final_low_resized/2.png' >",
"imageSource-02" : "<img src='images/final_low_resized/3.png' >"},
"001" : {
"id" : "001",
"subid" : {},
"name" : "2",
"price" : "*",
"composition" : "Состав: 2",
"description" : "100г продукта содержат: белок - 1.7г, углеводы - 5.0г Энергетическая ценность: 109.0ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 30 суток",
"imageSource-00" : "<img src='images/final_low_resized/1.png' >",
"imageSource-01" : "<img src='images/final_low_resized/2.png' >",
"imageSource-02" : "<img src='images/final_low_resized/3.png' >"},
"002" : {
"id" : "002",
"subid" : {},
"name" : "3",
"price" : "*",
"composition" : "Состав: 3",
"description" : "100г продукта содержат: белок - 9г, жир = 0.2г углеводы - 3.0г Энергетическая ценность: 286.1ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/1.png' >",
"imageSource-01" : "<img src='images/final_low_resized/2.png' >",
"imageSource-02" : "<img src='images/final_low_resized/3.png' >"},
"003" : {
"id" : "003",
"subid" : {},
"name" : "4",
"price" : "*",
"composition" : "Состав: 4",
"description" : "100г продукта содержат: белок - 1.7г, жиры - 0.1г, углеводы - 5.2г Энергетическая ценность: 25ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/4.png' >",
"imageSource-01" : "<img src='images/final_low_resized/4.png' >",
"imageSource-02" : "<img src='images/final_low_resized/4.png' >"},
"004" : {
"id" : "004",
"subid" : {},
"name" : "5",
"price" : "*",
"composition" : "Состав: 5",
"description" : "100г продукта содержат: белок - 2.18г, жир - 0.31г, углеводы - 5.81г Энергетическая ценность: 34.01ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/5.png' >",
"imageSource-01" : "<img src='images/final_low_resized/5.png' >",
"imageSource-02" : "<img src='images/final_low_resized/5.png' >"},
"005" : {
"id" : "005",
"subid" : {},
"name" : "6",
"price" : "*",
"composition" : "Состав: 6",
"description" : "100г продукта содержат: белок - 2.22г, жир - 0.76г углеводы - 8.09г Энергетическая ценность: 37.9ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/6.png' >",
"imageSource-01" : "<img src='images/final_low_resized/6.png' >",
"imageSource-02" : "<img src='images/final_low_resized/6.png' >"},
"006" : {
"id" : "006",
"subid" : {},
"name" : "7",
"price" : "*",
"composition" : "Состав: 7",
"description" : "100г продукта содержат: белок - 10.45г, жиры - 2.56г, углеводы - 5.31г Энергетическая ценность: 85.12ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/7.png' >",
"imageSource-01" : "<img src='images/final_low_resized/7.png' >",
"imageSource-02" : "<img src='images/final_low_resized/7.png' >"},
"007" : {
"id" : "007",
"subid" : {},
"name" : "8",
"price" : "*",
"composition" : "Состав: 8",
"description" : "100г продукта содержат: белок - 1.4г, жир - 10г, углеводы - 4.2г Энергетическая ценность: 111.8ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/8.png' >",
"imageSource-01" : "<img src='images/final_low_resized/8.png' >",
"imageSource-02" : "<img src='images/final_low_resized/8.png' >"},
"008" : {
"id" : "008",
"subid" : {},
"name" : "9",
"price" : "*",
"composition" : "Состав: 9",
"description" : "100г продукта содержат: белок - 24.3г, жир - 9.6г, углеводы - 5.0г Энергетическая ценность: 184.0ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/9.png' >",
"imageSource-01" : "<img src='images/final_low_resized/9.png' >",
"imageSource-02" : "<img src='images/final_low_resized/9.png' >"},
"009" : {
"id" : "009",
"subid" : {},
"name" : "10",
"price" : "*",
"composition" : "Состав: 10",
"description" : "100г продукта содержат: белок - 24.3г, жир - 9.6г, углеводы - 5.0г Энергетическая ценность: 184.0ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/10.png' >",
"imageSource-01" : "<img src='images/final_low_resized/10.png' >",
"imageSource-02" : "<img src='images/final_low_resized/10.png' >"},
"010" : {
"id" : "010",
"subid" : {},
"name" : "11",
"price" : "*",
"composition" : "Состав: 11",
"description" : "100г продукта содержат: белок - 16.2г, жир - 0.7г, углеводы - 0.8г Энергетическая ценность: 79ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 10 суток",
"imageSource-00" : "<img src='images/final_low_resized/11.png' >",
"imageSource-01" : "<img src='images/final_low_resized/11.png' >",
"imageSource-02" : "<img src='images/final_low_resized/11.png' >"},
"011" : {
"id" : "011",
"subid" : {},
"name" : "12",
"price" : "*",
"composition" : "Состав: 12",
"description" : "100г продукта содержат: белок - 1.7г, жир - 0.1г, углеводы - 5.2г Энергетическая ценность: 25ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 2&#176; до 6&#176; - 30 суток",
"imageSource-00" : "<img src='images/final_low_resized/12.png' >",
"imageSource-01" : "<img src='images/final_low_resized/12.png' >",
"imageSource-02" : "<img src='images/final_low_resized/12.png' >"},
"012" : {
"id" : "012",
"subid" : {},
"name" : "13",
"price" : "*",
"composition" : "Состав: 13",
"description" : "100г продукта содержат: белок - 1.7г, углеводы - 5.0г Энергетическая ценность: 164.6ккал",
"bestBefore" : "Срок годности и условия хранения: хранить при t от 0&#176; до 10&#176; - 45 суток",
"imageSource-00" : "<img src='images/final_low_resized/13.png' >",
"imageSource-01" : "<img src='images/final_low_resized/13.png' >",
"imageSource-02" : "<img src='images/final_low_resized/13.png' >"}
};
